### ISSUE TITLE
对Intelligent-Elderly-Care的一些咨询 

### ISSUE THREAD

**Issue by yaolp123** [Tang1705/Intelligent-Elderly-Care#14]
Github作者大牛：
   你好！  最近看了你的工程，非常感兴趣 但有一些不太懂， 可以添加QQ咨询分享一下吗？ 感谢！ 我的QQ：3101759565
  期待回复~

  谢谢。

**Comment by yaolp123** [comment]
why? github作者。

**Comment by Tang1705** [comment]
> why? github作者。

emmmm，要不你看看好友申请再说？

**Comment by yaolp123** [comment]
哈哈。抱歉。
